version: '3'

networks:
  backend-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16

services:
  backend:
    container_name: backend_container
    ports:
      - 5500:5500
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5500
      DATABASE_URL: 'mongodb://backend:backend@172.100.0.101:27017'
    networks:
      backend-net:
        ipv4_address: 172.100.0.100
    depends_on:
      - database
    volumes:
      - backend_volumes:/app/data

  database:
    container_name: backend_database
    ports:
      - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: backend
      MONGO_INITDB_ROOT_PASSWORD: backend
    networks:
      backend-net:
        ipv4_address: 172.100.0.101

volumes:
  backend_volumes:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/docker/volumes/week7practise_backend_volumes/_data'
